# ship_types.py
SHIP_TYPES = {
    0: "N/A",
    1: "Reservert",
    2: "Reservert",
    3: "Reservert",
    4: "Reservert",
    5: "Reservert",
    6: "Reservert",
    7: "Reservert",
    8: "Reservert",
    9: "Reservert",
    10: "Reservert",
    11: "Reservert",
    12: "Reservert",
    13: "Reservert",
    14: "Reservert",
    15: "Reservert",
    16: "Reservert",
    17: "Reservert",
    18: "Reservert",
    19: "Reservert",
    20: "Wing in grounde",
    21: "Wing in ground",
    22: "Wing in ground",
    23: "Wing in ground",
    24: "Wing in ground",
    25: "Wing in ground",
    26: "Wing in ground",
    27: "Wing in ground",
    28: "Wing in ground",
    29: "Wing in ground",
    30: "Fiske",
    31: "Tauing",
    32: "Tauing: lengde overstiger 200m eller bredde overstiger 25m",
    33: "Mudring eller undervannsoperasjoner",
    34: "Dykkeoperasjoner",
    35: "Militære operasjoner",
    36: "Seiling",
    37: "Fritidsbåt",
    38: "Reservert",
    39: "Reservert",
    40: "Høyhastighetsfartøy",
    41: "Høyhastighetsfartøy",
    42: "Høyhastighetsfartøy",
    43: "Høyhastighetsfartøy",
    44: "Høyhastighetsfartøy",
    45: "Høyhastighetsfartøy",
    46: "Høyhastighetsfartøy",
    47: "Høyhastighetsfartøy",
    48: "Høyhastighetsfartøy",
    49: "Høyhastighetsfartøy",
    50: "Losbåt",
    51: "Søk- og redningsfartøy",
    52: "Slepebåt",
    53: "Havnebåt",
    54: "Anti-forurensningsutstyr",
    55: "Lovhåndhevelse",
    56: "Reserve - Lokalt fartøy",
    57: "Reserve - Lokalt fartøy",
    58: "Medisinsk transport",
    59: "Ikke-kombattant skip",
    60: "Passasjerskip",
    61: "Passasjerskip",
    62: "Passasjerskip",
    63: "Passasjerskip",
    64: "Passasjerskip",
    65: "Passasjerskip",
    66: "Passasjerskip",
    67: "Passasjerskip",
    68: "Passasjerskip",
    69: "Passasjerskip",
    70: "Lasteskip",
    71: "Lasteskip",
    72: "Lasteskip",
    73: "Lasteskip",
    74: "Lasteskip",
    75: "Lasteskip",
    76: "Lasteskip",
    77: "Lasteskip",
    78: "Lasteskip",
    79: "Lasteskip",
    80: "Tankere",
    81: "Tanker",
    82: "Tanker",
    83: "Tanker",
    84: "Tanker",
    85: "Tanker",
    86: "Tanker",
    87: "Tanker",
    88: "Tanker",
    89: "Tanker",
    90: "Annen type",
    91: "Annen type",
    92: "Annen type",
    93: "Annen type",
    94: "Annen type",
    95: "Annen type",
    96: "Annen type",
    97: "Annen type",
    98: "Annen type",
    99: "Annen type",
}
